name: Update Option IV to Google Sheet

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: '0 22 * * 1-5' # Runs at 22:00 UTC on every day-of-week from Monday through Friday. (e.g., 6 PM New York time)

jobs:
  update-iv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
        run: python app/src/main.py
